name: Release Obsidian Plugin
on:
  workflow_dispatch:
    inputs:
      bump:
        default: false
        description: "Bump version based on semantic release"
        type: boolean
        required: false
      beta:
        default: false
        description: "Beta release"
        type: boolean
        required: false
  push:
    tags:
      - "*"

permissions:
  contents: write
jobs:
  release:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
    uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main
    with:
      PLUGIN_NAME: "highlighter"
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-version:
    if: ${{ inputs.bump }}
    uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
    with:
      PLUGIN_NAME: highlighter
      BETA: ${{ inputs.beta }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}